project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ".."
preserve_hierarchy: false
files:
  - source: src/PriceCheck/PriceCheck/Resource/source/PriceCheck_Localizable.json
    translation: src/PriceCheck/PriceCheck/Resource/translation/%two_letters_code%.json